/*
  Warnings:

  - You are about to drop the column `province` on the `Province` table. All the data in the column will be lost.
  - Added the required column `name` to the `Province` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE `Province` DROP COLUMN `province`,
    ADD COLUMN `name` ENUM('AMNATCHAROEN', 'ANGTHONG', 'BANGKOK', 'BURIRAM', 'CHACHOENGSAO', 'CHAINAT', 'CHAIYAPHUM', 'CHANTHABURI', 'CHIANGMAI', 'CHIANGRAI', 'CHONBURI', 'CHUMPHON', 'KALASIN', 'KAMPAENGPHET', 'KANCHANABURI', 'KHONKAEN', 'KRABI', 'LAMPANG', 'LAMPHUN', 'LOEI', 'LOPBURI', 'MAEHONGSON', 'MAHASARAKHAM', 'MUKDAHAN', 'NAKHONNAYOK', 'NAKHONPATHOM', 'NAKHONPHANOM', 'NAKHONRATCHASIMA', 'NAKHONSAWAN', 'NAKHONSITHAMMARAT', 'NAN', 'NARATHIWAT', 'NONGBUALAMPHU', 'NONGKHAI', 'NONTHABURI', 'PATHUMTHANI', 'PATTANI', 'PHACHINBURI', 'PHANGNGA', 'PHATTHALUNG', 'PHAYAO', 'PHETCHABUN', 'PHETCHABURI', 'PHICHIT', 'PHITSANULOK', 'PHRANAKHONSIAYUDHYA', 'PHRAE', 'PHUKET', 'PRACHUAPKHILIKHAN', 'RANONG', 'RATCHABURI', 'RAYONG', 'ROIET', 'SAKAEO', 'SAKONNAKHON', 'SAMUTPRAKARN', 'SAMUTSAKHON', 'SAMUTSONGKHAM', 'SARABURI', 'SATUN', 'SISAKET', 'SINGBURI', 'SONGKHLA', 'SUKHOTHAI', 'SUPHANBURI', 'SURATTHANI', 'SURIN', 'TAK', 'TRAD', 'TRANG', 'UBONRATCHATHANI', 'UDONTHANI', 'UTHAITHANI', 'UTTARADIT', 'YALA', 'YASOTHON') NOT NULL;
